In [10]:
!cat /home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_0_model_model1a/_threshold_2.6/_grf_cluster0/zstat1_localmax.txt

Cluster Index	Value	x	y	z

In [11]:
import glob

In [16]:
fns = glob.glob('/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_*_model_model*/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt')

In [17]:
from IPython.display import display

In [18]:
import pandas

In [19]:
for fn in sorted(fns):
    print fn
    display(pandas.read_csv(fn, sep='\t'))

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_0_model_model1a/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_0_model_model1b/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_0_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_0_model_model2/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_1_model_model1a/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

    Cluster Index  Value    x    y    z  Unnamed: 5
0               5   4.22   38  145  108         NaN
1               5   3.88   49  143  124         NaN
2               5   3.63   46  143  119         NaN
3               5   3.60   45  158  102         NaN
4               5   3.57   49  140  110         NaN
5               5   3.43   43  162  102         NaN
6               4   3.65   40   76  123         NaN
7               4   3.56   42   75  106         NaN
8               4   3.53   43   83  108         NaN
9               4   3.52   43   73  104         NaN
10              4   3.51   44   82  106         NaN
11              4   3.47   41   76  112         NaN
12              3   3.66   51  186   72         NaN
13              3   3.56   51  186   67         NaN
14              3   3.44   50  185   79         NaN
15              3   3.40   54  186   64         NaN
16              3   3.40   49  183   79         NaN
17              3   3.36   70  187   96         NaN
18              2   3.63  142   72  114         NaN
19              2   3.56  138   70  122         NaN
20              2   3.56  136   76  110         NaN
21              2   3.50  137   70  125         NaN
22              2   3.37  140   82  128         NaN
23              2   3.37  138   81  129         NaN
24              1   3.57  139  146  108         NaN
25              1   3.38  132  140  110         NaN
26              1   3.21  136  149   99         NaN
27              1   3.20  136  149  103         NaN
28              1   2.95  129  152  115         NaN
29              1   2.87  120  150  123         NaN

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_1_model_model1b/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_1_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

    Cluster Index  Value    x    y    z  Unnamed: 5
0               4   4.06   38  145  108         NaN
1               4   3.78   49  143  124         NaN
2               4   3.47   46  143  119         NaN
3               4   3.41   45  158  101         NaN
4               4   3.32   49  140  110         NaN
5               4   3.25   54  146   97         NaN
6               3   3.55   42   73  104         NaN
7               3   3.49   42   75  106         NaN
8               3   3.45   41   76  123         NaN
9               3   3.37   37   78  120         NaN
10              3   3.37   42   76  111         NaN
11              3   3.36   47   74  103         NaN
12              2   3.56   51  186   71         NaN
13              2   3.55   51  186   67         NaN
14              2   3.38   54  186   64         NaN
15              2   3.32   49  183   79         NaN
16              2   3.32   50  185   79         NaN
17              2   3.30   83  192   86         NaN
18              1   3.57  142   72  114         NaN
19              1   3.57  138   70  122         NaN
20              1   3.53  137   70  125         NaN
21              1   3.44  136   76  111         NaN
22              1   3.43  140   82  128         NaN
23              1   3.38  145   72  116         NaN

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_1_model_model2/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_2_model_model1a/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_2_model_model1b/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

    Cluster Index  Value    x    y    z  Unnamed: 5
0               3   3.61  142  100  125         NaN
1               3   3.51  119   98  136         NaN
2               3   3.46   78   65  126         NaN
3               3   3.40  138  102  129         NaN
4               3   3.35  117  104  142         NaN
5               3   3.30   74   89  123         NaN
6               2   3.50  104   32   58         NaN
7               2   3.48  107   26   68         NaN
8               2   3.37  128   38   62         NaN
9               2   3.21  117   31   60         NaN
10              2   3.19  112   39   57         NaN
11              2   3.18  114   27   74         NaN
12              1   3.49   56   80  137         NaN
13              1   3.13   64   92  121         NaN
14              1   3.10   59   82  125         NaN
15              1   2.94   44  100  107         NaN
16              1   2.89   64   88  138         NaN
17              1   2.88   52   83  124         NaN

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_2_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_2_model_model2/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_3_model_model1a/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_3_model_model1b/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_3_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

   Cluster Index  Value    x   y   z  Unnamed: 5
0              1   3.68   82  73  20         NaN
1              1   3.43  108  83  19         NaN
2              1   3.14  104  63  20         NaN
3              1   3.04  109  64  16         NaN
4              1   2.98   93  72  19         NaN
5              1   2.91  100  71  16         NaN

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_3_model_model2/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_4_model_model1b/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_4_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

    Cluster Index  Value    x    y   z  Unnamed: 5
0               2   3.75  137  128  84         NaN
1               2   3.57  141  128  84         NaN
2               2   3.48  143  129  82         NaN
3               2   3.16  114  130  84         NaN
4               2   2.94  112  133  76         NaN
5               2   2.94  138  127  77         NaN
6               1   3.38   72  145  77         NaN
7               1   3.35   74  137  69         NaN
8               1   3.18   82  149  80         NaN
9               1   3.09   68  139  65         NaN
10              1   3.05   74  149  78         NaN
11              1   3.00   80  141  77         NaN

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_5_model_model1b/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_5_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

Empty DataFrame
Columns: [Cluster Index, Value, x, y, z, Unnamed: 5]
Index: []

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_6_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

   Cluster Index  Value    x    y   z  Unnamed: 5
0              1   3.68  158  103  58         NaN
1              1   3.57  144  115  61         NaN
2              1   3.54  149  103  67         NaN
3              1   3.37  145  107  63         NaN
4              1   3.27  147  125  55         NaN
5              1   3.22  150  124  54         NaN

/home/gdholla1/projects/bias/data/derivatives/glm_fits_level3_no_ppi/grf_localmax_txt_file/_contrast_7_model_model1c/_threshold_2.3/_grf_cluster0/zstat1_localmax.txt

    Cluster Index  Value    x    y   z  Unnamed: 5
0               2   3.44   98   22  84         NaN
1               2   3.25  122   29  79         NaN
2               2   3.24   97   23  88         NaN
3               2   3.13  135   37  74         NaN
4               2   3.08   93   25  72         NaN
5               2   3.05  104   23  82         NaN
6               1   3.53  108  107  91         NaN
7               1   3.50  103  114  88         NaN
8               1   3.50  105  113  89         NaN
9               1   3.32  107  103  92         NaN
10              1   3.32   99  124  86         NaN
11              1   2.77  101  110  80         NaN